### ISSUE TITLE
Package could not be found in any version

### ISSUE THREAD

**Issue by Merisho** [rodzadra/yii2-geolocation#1]
Hello. I have problem with composer installation.

Problem 1
    - The requested package rodzadra/geolocation could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

I was trying require "--dev" but it doesn't help.

SOLUTION:
--prefer-source

**Comment by penraeth** [comment]
I'm not having any luck using --prefer-source, --prefer-dist or anything else. Is this issue truly solved?

**Comment by Merisho** [comment]
Check this and try to configure your minimum-stability setting
https://getcomposer.org/doc/04-schema.md#minimum-stability

And if will happen anything else ("Options" section)
https://getcomposer.org/doc/03-cli.md#require

**Comment by penraeth** [comment]
Thanks Merisho
I tried changing min stability to dev with same result. Ended up manually installing.
