### ISSUE TITLE
Variable "format"

### ISSUE THREAD

**Issue by dmdropkick** [rodzadra/yii2-geolocation#2]
In configuration:

> 1) In your config/main.php
> 'components'=>[
>     'geolocation' => [ 
>         'class' => 'rodzadra\geolocation\Geolocation',
>         'config' => [
>             'provider' => '[PLUGIN_NAME]',
>             'format' =>  '[SUPORTED_PLUGIN_FORMAT]',
>             'api_key' => '[YOUR_API_KEY],
>         ],
>     ],
> ],

Variable "format", but need "return_format".

**Comment by rodzadra** [comment]
Thank you @dmdropkick. I correct change the var name to return_formats on the README and code.
