### ISSUE TITLE
using freegeoip 

### ISSUE THREAD

**Issue by aidonsnous** [rodzadra/yii2-geolocation#3]
Hello;

Freegeoip doesn't request you or give you an api key to use it database; but following the example you give for the configuration the api key is present; so for freegeoip which value should I put there? I visited the website of freegeoip there is nothing like api key.

**Comment by rodzadra** [comment]
Hello @MagSag!

To use FreeGeoIP:

The "API Key" is a optional parameter. To use the freegeoip plugin, just configure it:

In your config/main.php


```
'components'=>[
    'geolocation' => [ 
        'class' => 'rodzadra\geolocation\Geolocation',
        'config' => [
            'provider' => 'freegeoip',
            'return_formats' =>  'JSON',
        ],
    ],
],
```

and use

```
<?php
  print_r(yii::$app->geolocation->getInfo());
?>
```
