### ISSUE TITLE
error Getting unknown property: yii\web\Application::geolocation'

### ISSUE THREAD

**Issue by aidonsnous** [rodzadra/yii2-geolocation#4]
Here is the error I am getting:

> exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\web\Application::geolocation' in /home/goweb/vendor/yiisoft/yii2/base/Component.php:143
> Stack trace:
> #0 /home/goweb/vendor/yiisoft/yii2/di/ServiceLocator.php(73): yii\base\Component->__get('geolocation')
> #1 /home/goweb/views/layouts/main.php(447): yii\di\ServiceLocator->__get('geolocation')
> #2 /home/goweb/vendor/yiisoft/yii2/base/View.php(325): require('/home/goweb/vi...')
> #3 /home/goweb/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/goweb/vi...', Array)
> #4 /home/goweb/vendor/yiisoft/yii2/base/Controller.php(392): yii\base\View->renderFile('/home/goweb/vi...', Array, Object(app\controllers\ActiviteController))
> #5 /home/goweb/vendor/yiisoft/yii2/base/Controller.php(378): yii\base\Controller->renderContent('<div class="tim...')
> #6 /home/goweb/controllers/ActiviteController.php(947): yii\base\Controller->render('timeline', Array)
> #7 [internal function]: app\controllers\ActiviteController->actionTimeline('0', 'J32y')
> #8 /home/goweb/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
> #9 /home/goweb/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
> #10 /home/goweb/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('timeline', Array)
> #11 /home/goweb/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('activite/timeli...', Array)
> #12 /home/goweb/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
> #13 /home/goweb/public_html/index.php(13): yii\base\Application->run()
> #14 {main}

I don't know what's wrong?

**Comment by rodzadra** [comment]
Have you installed through composer?
